// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgrsngtophlchvdpbvge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBncnNuZ3RvcGhsY2h2ZHBidmdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2ODAxNTAsImV4cCI6MjA2MzI1NjE1MH0.myAhv3ihmo6OAe8oQmAwIaNlmCOuRcMS4i-ZfXDIjh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);